version: '3.9'
# Defining the compose version
services:

 # Nginx server
 nginx:
 
   # Build context
   build: ./nginx
   
   # Mapping machine and container ports
   ports:
     - 1337:80
     - 443:443
    
   links:
     - "app"
     
   # Storage volumes
   volumes:
     - static_volume:/home/app/blog/static
     - media_volume:/home/app/blog/mediafiles
   depends_on:
     - app
   restart: "on-failure"
   
 # Django application
 app:
 
   # Build context
   build: ./
   
   # Build commands
   command: sh -c "python manage.py makemigrations &&
                   python manage.py migrate &&
                   python manage.py collectstatic &&
                   gunicorn personal-portfolio.wsgi:application --bind 0.0.0.0:8000"
                   
   # Storage volumes
   volumes:
     - static_volume:/home/app/blog/static
     - media_volume:/home/app/blog/mediafiles
     
   # Exposing port 8000
   expose: 
   - 8000
   restart: "on-failure"
      
volumes:
 postgres_data:
 static_volume:
 media_volume: