version: '3.9'
# Defining the compose version
services:

 # Nginx server
 nginx:
 
   # Build context
   build: ./nginx
   
   # Mapping machine and container ports
   ports:
     - 80:80
     - 443:443
    
   links:
     - "app"
     
   # Storage volumes
   volumes:
     - static_volume:/home/app/blog/static
     - media_volume:/home/app/blog/mediafiles
     - ./etc/nginx/templates:/etc/nginx/templates:ro
     - ./etc/letsencrypt:/etc/letsencrypt
     - ./certbot/data:/var/www/certbot
     - /var/log/nginx:/var/log/nginx
   depends_on:
     - app
   restart: "on-failure"

 certbot:
   container_name: certbot
   image: certbot/certbot:latest
   depends_on:
     - nginx
   command: >-
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email dariocantella@gmail.com --agree-tos --no-eff-email
             -d cantella.hopto.org
   volumes:
     - ./etc/letsencrypt:/etc/letsencrypt
     - ./certbot/data:/var/www/certbot
   
 # Django application
 app:
 
   # Build context
   build: ./
   
   # Build commands
   command: sh -c "python manage.py makemigrations &&
                   python manage.py migrate &&
                   python manage.py collectstatic &&
                   gunicorn personal-portfolio.wsgi:application --bind 0.0.0.0:8000"
                   
   # Storage volumes
   volumes:
     - static_volume:/home/app/blog/static
     - media_volume:/home/app/blog/mediafiles
     
   # Exposing port 8000
   expose: 
   - 8000
   restart: "on-failure"
      
volumes:
 postgres_data:
 static_volume:
 media_volume: